name: Express APP  CI

on:
    push:
      branches-ignore: [main] 
    pull_request:
      branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.0'
          cache: 'npm'
     
      - name: Install dependencies
        run: npm ci
      - name: Build CSS
        run: npm run build:css
      - run: npm run build --if-present
      # - run: npm test
      - name: Test Docker build
        run: docker build --platform=linux/amd64 -t test-image .
    

        
