name: Auto PR Creation

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
      - name: Create Pull Request
        run: gh pr create --title "Auto PR from ${{ github.ref_name }}" --body "Auto-created PR" --base main --head ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
